### ISSUE TITLE
field.Size seems to be incorrect for some nested fields

### ISSUE THREAD

**Issue by ashmind** [microsoft/clrmd#101]
For example,
```
struct S { int i; }
class C { S s; }
```

On x86 I get `12` as `field.Size`  for `C.s`, but size of `C` itself is also `12` -- `C.s` should be `4`.
I assume `field.Size` doesn't consider nested values and adds overhead for object header.

Is there a way to get a proper field size here?

**Comment by leculver** [comment]
Ah I was wrong in that previous statement.  It looks like this is the offending code:  https://github.com/Microsoft/clrmd/blob/bbde79ff1d816d15697ae12dc7a5982682a83919/src/Microsoft.Diagnostics.Runtime/src/Desktop/DesktopInstanceField.cs#L259

The problem here is that there's no API in the dac which hands out the correct size of a field.  We would have to run a layout algorithm to determine the size of a struct field.  Definitely a bug, but not sure I want to tackle this one until after I do a lot of refactoring in ClrMD.

**Comment by leculver** [comment]
Fixed, will be in the next ClrMD 1.1 release.
