### ISSUE TITLE
Is it possible to get the DeclaringType?

### ISSUE THREAD

**Issue by felipepessoto** [Microsoft/clrmd#102]
I can't find a way to get the DeclaringType, like Type.DeclaringType. To get the outer class:

```
public abstract class OuterClass
{
    public abstract class MyClassA 
    {
        public abstract int m(); 
    }
}
```

I have a object MyClassA, how do I get OuterClass?

**Comment by leculver** [comment]
Good question.  I don't believe this is possible to do with ClrMD.  The underlying APIs that ClrMD is built on top of do not support this.  I will leave this issue open while I double check whether there's a way to do this at all.

**Comment by leculver** [comment]
Unfortunately it's not directly possible to do this with ClrMD.  The underlying Dac APIs do not support this.  It is possible to get IMetaDataImport that can give you this answer via the module.

I do not intend to implement this in ClrMD at this time since the underlying APIs we use don't support it.
