### ISSUE TITLE
Please provide API to automatically collect memory snapshots

### ISSUE THREAD

**Issue by mitikov** [Microsoft/clrmd#113]
Hey folks, 

Please provide a functionality to automatically collect memory snapshot & save it to the given location.
While existing API to attach to the process (DataTarget.AttachToProcess) it allows on-fly investigation.

In other words, the code what to look for must be already developed.

While there are many scenarios where you do not know what you are hunting for during collection, like:

A) Random CPU spikes
B) Pool starvations 
C) Hang API calls for no good reason

While a majority of those could be collected via ProcDump, here are the cases when not:
1) The exception happens on the build server you do not have much access to - you can collect artifacts
2) The offensive API hangs deep inside the shipped assembly you have no control over

Our builds are hanging on the build server once in a while. Since triggering build again fixes the issue in 99% of the cases, we want to figure out the cause.

Right now we are capturing call-stacks once in N minutes to track the bad guy.
In a few days we'll know which code & will have to adjust the clrMD part to log more data =\

It would be much better if there was a collect API to capture snapshot based on C# condition.

Thanks.

**Comment by leculver** [comment]
I try to not add too many "utility" like code and functions to ClrMD itself.  I don't think I want to own and maintain something like this in ClrMD, because doing this correctly is actually a lot of work and will be difficult to maintain long term.

I'm planning to split out some "helper" functionality into a side DLL where things like this could potentially go (tracked by https://github.com/Microsoft/clrmd/issues/203).  If you or someone decided to build code that does this I would consider adding it to this side library when it's created, but I don't plan to tackle this one myself, so I'm going to close the issue here.

Thanks for the suggestion though!
