### ISSUE TITLE
ClrType.ComponentType is set to 'ERROR' instead of array element type.

### ISSUE THREAD

**Issue by JeffCyr** [microsoft/clrmd#115]
When a type is obtained first by ClrField.Type, it's ComponentType property is not always set properly.

The issue is reproducible with this target process:

```c#
using System;
using System.Threading;

namespace ClrMdBugRepro
{
    public class Test
    {
        public ArraySegment<byte> Field1;
    }

    class Program
    {
        static void Main(string[] args)
        {
            var test = new Test
            {
                Field1 = new ArraySegment<byte>(new byte[10]),
            };
            Thread.Sleep(-1);
        }
    }
}
```

And this clrmd code sample:
```c#
    var testType = heap.EnumerateTypes().Where(t => t.Name == "ClrMdBugRepro.Test").First();
    var segmentType = testType.GetFieldByName("Field1").Type;
    var arrayType = segmentType.GetFieldByName("_array").Type;
    
    Console.WriteLine(arrayType.ComponentType.Name); // ==> Output: ERROR
```

The workaround is to ensure all types are constructed by ClrHeap.GetObjectType first, then ClrField.Type will return the cached instance.

**Comment by JeffCyr** [comment]
@leculver Do you have an idea of what the fix would be for this issue?

**Comment by leculver** [comment]
I don't know off the top of my head.  The big problem here is that the dac private interface doesn't react well to generic types, which makes things very difficult when trying to expose a sensible API on top of it.  Without having debugged this, we _should_ be able to give you a concrete ClrType in this case since it falls under the category of "DesktopGCHeap.GetBasicType".  As long as the array type knows its CorElementType anyway...

Keep in mind that (unfortunately) there are some issues like this we just can't fix in Desktop CLR easily.  I'm hoping we can do a much better job of this in .Net Core in the future though.

Unfortunately I can't take a look at this right now.  It's on my todo list though.

**Comment by JeffCyr** [comment]
Alright thanks,

Just a note for future you then: This used to work with the first release of clrmd before the separate repository was created. It also works with the current version if the ClrType is fetched the first time with ClrHeap.GetObjectType, this issue is when the ClrType is initialized by ClrField.Type, the ClrType without ComponentType is cached.

**Comment by leculver** [comment]
(Sorry for the recycled message here, I'm trying to tear through the remaining bugs I have.)

I have some vague plans to revisit a lot of the internals of the ClrMD type system in ClrMD 1.1 or 1.2 (which is a while out). One of the goals of that planned work is to simplify and rework a lot of the internal parts of ClrMD, especially around some of the really bad heuristics that you are running into here.

I'm going to delay looking into/fixing this bug until I either do that work, or decide that I won't go ahead with a rewrite. (In the case where I don't rewrite some of the internals I will still *try* to tackle this bug as a one-off fix.)

**Comment by leculver** [comment]
After taking another look here, I'm closing this one as unfixable.  There's nothing much I can do about this problem, though the upcoming 2.0 release will make ComponentType == null much less common.

I'm planning to try to do some work in .Net Core 5 to have mscordaccore.dll add a function to give us the component typehandle given an array.  This should fix the issue 

> The workaround is to ensure all types are constructed by ClrHeap.GetObjectType first, then ClrField.Type will return the cached instance.

I don't think we can do this.  The only way would be to enumerate the heap before ever returning any fields, but that would just take too long before the api is usable.  We'll have to pursue a real CLR fix for this issue, because that's where the issue really is.)
