### ISSUE TITLE
Cross-Platform Analysis?

### ISSUE THREAD

**Issue by daddycocoaman** [microsoft/clrmd#1229]
Hi,

Thanks for creating and maintaining ClrMD. It's been pretty useful for me in a lot of cases. 

I know that ClrMD is cross platform, but I was wondering if it's possible to analyze memory dumps from a different OS (like analyzing Windows Minidumps on Linux). Or is that impossible due to having to load the specific native library which won't be able to list the `ClrVersion` from another OS? Thanks for any info or suggestions.

**Comment by leculver** [comment]
>  Or is that impossible due to having to load the specific native library which won't be able to list the ClrVersion from another OS?

ClrMD uses a native library for debugging.  The .Net runtime builds a few of these debugging libraries as cross-OS or cross-architecture, but it doesn't fully build the entire matrix.  Debugging Windows dumps on Linux, for example, is not supported because they do not build that particular configuration.  Debugging Linux dumps on Windows, is available because they do build that one.

**Comment by daddycocoaman** [comment]
@leculver Thanks for the response, and I didn't want to reopen this issue, but can you point me to where that matrix is defined? I haven't been able to locate it so far.

**Comment by leculver** [comment]
@tommcdon Do you remember where in the docs or github issues we define the matrix of supported debugger architecture/target architecture combos?

**Comment by tommcdon** [comment]
We have the following GH issue tracking the current support matrix: https://github.com/dotnet/runtime/issues/77433

**Comment by daddycocoaman** [comment]
@tommcdon @leculver Thanks!
