### ISSUE TITLE
Access violation in finalizers

### ISSUE THREAD

**Issue by 0xd4d** [Microsoft/clrmd#126]
It seems the bug is that DacLibrary's dtor is called before other dtors that depend on that library being present in memory.

https://github.com/Microsoft/clrmd/blob/e37fb3a9e419ae09c7e2ac0a66ba0afb4c264b6c/src/Microsoft.Diagnostics.Runtime/datatarget.cs#L1261

vs

https://github.com/Microsoft/clrmd/blob/e37fb3a9e419ae09c7e2ac0a66ba0afb4c264b6c/src/Microsoft.Diagnostics.Runtime/ComWrappers/CallableCOMWrapper.cs#L82

which tries to do this:

https://github.com/Microsoft/clrmd/blob/e37fb3a9e419ae09c7e2ac0a66ba0afb4c264b6c/src/Microsoft.Diagnostics.Runtime/ComWrappers/CallableCOMWrapper.cs#L42

**Comment by leculver** [comment]
Much appreciated, this was on my todo list to tackle today.

Also, please note the repo isn't in a fully finished and tested state.  I had to merge it over early to do some (internal) build work to support the new build system.  Please expect bugs and crashes for a short while as I finish build work and get this fully tested.  (Always happy for bug reports though!)

**Comment by leculver** [comment]
This should be fixed with the most recent pull request merge.  I haven't specifically gone to test this so please do reopen this issue if you hit it again.  It's still on my todo list to ensure proper addref/release counts and that the daclibrary doesn't free the library until everything is unloaded.

**Comment by 0xd4d** [comment]
I think it can only happen when the application is exiting in which case the dtors should check `Environment.HasShutdownStarted` and not do any cleanup if it's true.

**Comment by leculver** [comment]
Thank you, I've reopened the issue and will take a closer look this week.

**Comment by 0xd4d** [comment]
I added a PR https://github.com/Microsoft/clrmd/pull/137

**Comment by leculver** [comment]
Thank you for the PR!  I decided to go a slightly different direction to fix this:  https://github.com/Microsoft/clrmd/commit/4a16cfa3c42a1c5f8899aa772543a72dd9b63622

Instead of putting Dispose on ClrRuntime, I wanted to put that on DacLibrary instead, as I use DacLibrary directly in some of my projects.  I've also split out the code to actually release the library into its own class with its own lifetime.

I'm not done with lifetime management here.  I still want the call to DataTarget.Dispose to clean up everything instead of waiting for finalizers.  I also need to go through and fully test all the addref/release to make sure everything is clean.

For now though, this should stop the AVs.  If it doesn't please let me know and I'll reopen the issue and take another swing.

**Comment by leculver** [comment]
As of https://github.com/Microsoft/clrmd/commit/441d779d5636961aa0c62473f1a9c0ed0abcf5db, I think this work is completed.  I've cleaned up all of the semantics around how DacLibrary and the COM interfaces it uses are produced.  As of this change there's no outstanding work in this area and all addref/release in the library are fully tested.

Let me know if you run into any more issues related to this!
