### ISSUE TITLE
IntPtr(long) ctor throws OverflowException

### ISSUE THREAD

**Issue by 0xd4d** [Microsoft/clrmd#162]
Note that this issue has nothing to do with the C# overflow check option that used to be enabled in the clrmd csproj file. It's thrown in the IntPtr ctor.

Microsoft.Diagnostics.Runtime.LiveDataReader

eg. `public bool ReadMemory(ulong address, byte[] buffer, int bytesRequested, out int bytesRead)` calls `new IntPtr((long)address)` which throws in the IntPtr ctor when `address` has bit 31 set and it's a 32-bit process.

Test: Execute this in a 32-bit process: `new IntPtr(0x0000000080000000L)`

**Comment by leculver** [comment]
Thanks for the report.  That's an annoying issue to fix...  I could swap to UIntPtr for LiveDataReader, but I worry there's other places that have this issue.  I'm thinking of doing something like this:

    public static IntPtr AsIntPtr(this ulong address)
    {
        unsafe
        {
            void* ptr = (void*)address;
            IntPtr test = new IntPtr(ptr);
            return test;
        }
    }

Then just use "addr.AsIntPtr()" instead of "new IntPtr((long)addr)".  Can you think of another way to do this?

**Comment by 0xd4d** [comment]
I usually use the "safe" version: `IntPtr.Size == 4 ? new IntPtr((int)address) : new IntPtr((long)address)`

**Comment by leculver** [comment]
Ah!  I was making it too complicated.  Thank you.
