### ISSUE TITLE
ModuleInfo.IsRuntime looks a bit weird

### ISSUE THREAD

**Issue by isakiev** [microsoft/clrmd#199]
it is error-prone as the flag initialization is separated from its creation
e.g. if `EnumerateModules()` is called before `InitVersions()` no flags will be initialized at all.

just curious if it is still required for anything.
if not, can it be marked as obsolete and removed in the next versions?

**Comment by leculver** [comment]
I think a lot of ModuleInfo may need to be reworked for 1.1 (or 1.2).  ModuleInfo is a really odd class, because it's expected that a consumer of ClrMD may need to implement it themselves, yet it's built in a really dumb way if that's the case.  A lot of things aren't virtual, and it is a bad mix of lazy initialization and not.

As part of some other work for the CLR team, I've started looking at [reworking IDataReader](https://github.com/leculver/clrmd/blob/sos/src/Microsoft.Diagnostics.Runtime/src/DataReaders/IDataProvider.cs), which will require me to rewrite some portion of ModuleInfo.  All of [the branch I'm experimenting in](https://github.com/leculver/clrmd/tree/sos) is definitely not final

**Comment by isakiev** [comment]
@leculver thanks for the details! it will be very interesting to take a look at the sos-branch)

**Comment by leculver** [comment]
Fixed in ClrMD 2.0 2fa6466600f1c66c0ca658fbc3e50e3093abd841.
