### ISSUE TITLE
Provide API to get ComponentElementType for ClrType

### ISSUE THREAD

**Issue by Zvirja** [Microsoft/clrmd#20]
Currently you can get ComponentType for array only, no way to get ComponentElementType.

Extend API to return that value.

**Comment by leculver** [comment]
Can you provide an example of what you are looking to get here?  I'm not 100% sure what you are asking to expose through the public surface.

**Comment by Zvirja** [comment]
My issue was following. I have array object address and ClrHeap object. Depending on whether this is array of `object` or `struct`, I need to use `GetArrayElementValue` or `GetArrayElementAddress` API.

Now I need to somehow figure out what kind of data this array contain. I can use `arrayObjType.ArrayComponentType.ElementType == Struct`, but it looks like that if `Microsoft.Diagnostics.Runtime.Desktop.DesktopArrayType.m_arrayElementType` was exposed publicly, that would allow to do that better.

Now I'm not sure that this approach will be correct (because component type doesn't map 1:1 to arrayElementType).

What do you think about all this? I'm just looking for the best way to check whether this array is of structs or simple values.

**Comment by leculver** [comment]
Sorry I just got back around to this one.  Checking to see if something is an array of structs or primitives should be done like this:

`bool isArrayOfStruct = clrType.IsArray && clrType.ComponentType.IsValueClass;
bool isArrayOfPrimitives = clrType.IsArray && clrType.ComponentType.IsPrimitive;`

IsValueClass returns whether ElementType matches ClrElementType.Struct exactly.  (Perhaps this terminology of 'ValueClass' is confusing...maybe calling it 'Struct' instead would have been more clear.  However this is what it's called around here and I kept the terminology.)

Does that address your concern?

**Comment by Zvirja** [comment]
If `clrType.ComponentType` never returns `null`, I'm fine with this approach and you can close this.

If sometimes `clrType.ComponentType` could be null while `clrType.m_arrayElementType` is not null - I'd like to have both properties to use the second one as a fallback.

**Comment by leculver** [comment]
ClrType.ComponentType should never be null when ClrType.IsArray returns true.  If it ever returns null for an array type, then that is a bug and you should open an issue for it.

(However, we may create a "fake" ClrType if the underlying Dac APIs cannot construct the correct type for it.  Rare, but it happens.  In that case you may get System.Object or System.ValueType instead of the actual type.  In practice this should be very rare, and it's not something I can make work correctly without changing CLR itself.)

I will double check this afternoon to make sure we correctly set ComponentType even in this rare failure case.

**Comment by leculver** [comment]
Changeset ab13312014e91a7146e406fde6b1cdef92bf59b2 ensures we always have a type in these cases.
