### ISSUE TITLE
Why do we need two separate projects for the tests?

### ISSUE THREAD

**Issue by isakiev** [Microsoft/clrmd#201]
What kind of problem is being solved this way?
The question is probably for @mitikov.

**Comment by leculver** [comment]
The .Tests project is more of an integration test, requiring a lot of moving parts to work correctly, including having generated test binaries.  The UnitTest project are standalone tests that do not require running "build_test_assets.cmd" (or whatever I named it).

For right now, this is SUPER useful to me because our internal infrastructure can't really handle generating test binaries (and putting them in a blob to download will be mildly expensive).  By having a separate UnitTests project I can have the unit tests run on every pull request and every checkin automatically without having to create a test resource binary drop.

I might merge those projects later if I figure out a way to do this without needing to payload tests.  (It's unfortunate that .Net Core doesn't support codedom...  I originally had them all working by compiling them and running as I went, but I've not come up with a good approach in .Net Core to do this without batch files and dependencies.)

**Comment by isakiev** [comment]
thank you for the info

**Comment by mitikov** [comment]
Yep, my idea was similar - to have unit and integration tests separate.

Integration tests to ensure API fetches data corretly from existing source.
While getting to know older ClrMD version, I was wondering how should code behave with the input data, so I had to capture snapshots with prototyped objects and inspect runtime values with debugger attached.

I aim integration test to be able answer most of the questions as coverage increases.

Today VS can locate API usages  -> would include integration tests -> show what to expect from the input data.

While unit tests are lightweight and focused on implementation logic, like how ClrMD treats in-process data.

As unit tests do not need to physically open memory snapshot, they are super fast with proper isolation - could be run in parallel.

Sorry for a late reply, Happy New Year 🤪
