### ISSUE TITLE
Add tags to indicate which exact commit is pushed to Nuget

### ISSUE THREAD

**Issue by Zvirja** [Microsoft/clrmd#22]
I've noted that recently you pushed new version of the library to [NuGet](https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime). However, this repository doesn't contain any tag.

It would be cool to track that, so we can better understand which changes were pushed. I'd suggest use tagging for that.

**Comment by leculver** [comment]
This will be done when we push nugget releases. However there is not a current tag because we released the last NuGet package we had not created this project and released source. Currently there is no tag/commit for what has been released through NuGet since there's no checking which corresponds to that release.
