### ISSUE TITLE
Add API to get type information for the generic type instance

### ISSUE THREAD

**Issue by zvirja** [Microsoft/clrmd#23]
Currently, if you get type for the generic instance, type is resolved correctly, e.g. `List<string>`. That is because MethodTable is unique for each generic instantiation and contains information which particular types were substituted.

It would be great if `ClrType` could return list of types for closed generic type with exact types that were substituted. 
Prototype:

```
var type = heap.GetObjectType(listObj);
var name = type.Name; //System.Collections.Generic.List<System.String>
var substitutedTypes = type.SubstitutedTypesForGenerics; //List, count: 1.
var firstName = substitutedTypes.First().Name; //System.String.
```

I've briefly checked the SOSDac API and found that likely it doesn't provide us with such opportunities. However, you mentioned that you will introduce usage of `ICorDebug` API. I hope it's capable of extracting such information.

Close this ticket if that is impossible with both `ISOSDac` and `ICorDebug` APIs (or with some other ways).

**Comment by leculver** [comment]
I will take a look and see what can be done here.  In general, ISOSDac does not support generics in any meaningful way.  ICorDebug does give this type of information correctly, but the difficult part will be linking a ClrType to a specific ICorDebugClass instance (ISOSDac and ICorDebug work at different levels of abstraction, and stitching the two interfaces together will be non-trivial).

It'll be a while before I add ICorDebug support to ClrMD, so I'll leave the issue open until I have added it and taken a look to see if this is possible.

**Comment by leculver** [comment]
I failed in my attempt to fix this back in 2015...  I plan to revisit this problem in the future, but for now I'm going to mark this Won't Fix.  (More like "Can't Fix", because the underlying APIs I use don't support this.)

Specifically the main thing I want to do in clrmd 1.2 is rework a lot of ClrMD's internals, including how we handle generics.  However, the biggest problem I face is that the dac private interface doesn't have a good way to answer these questions, so we will have to see whether it's possible to do anything here.
