### ISSUE TITLE
Object and field representation (dynamic and otherwise)

### ISSUE THREAD

**Issue by leculver** [Microsoft/clrmd#24]
ClrMD should provide a more sensible way to access fields, values, and so on.  Instead of relying on "object GetValue".  Here is some of the previous discussion (edited for brevity and clarity).  I will refrain from putting my opinion here.

There are several primary topics of discussion for this design:
1. Interior flag.
2. Getting a single field/object value.
3. Getting a chain of values.
4.  Enumeration array contents.
5.  Enumeration of advanced containers. (List/Dictionary/etc.)
6.  Converting more complex structures such as DateTime, Guid, etc.

@Zvirja starts:

I analyzed the way with the `dynamic` keyword and liked it (even added to todo), however decided to proceed with a "static" direction. I defined the `IPtr` interface that provides address, type and heap and build a set of different extension methods around that. One kind of extensions allows to read fields from the object.
Below are examples of code that is used to achieve the different tasks.

Read fields:

```
IPtr ptr; //here we somehow get the object.
int intValue = ptr.GetInt("intField", /*interior true/false*/)
string strValue = ptr.GetString("stringField");
IPtr refValue = ptr.GetRef("ptrField");
IPtr structPtr = ptr.GetStruct("structField");
```

Read chains:

```
int intValue = ptr.GetSimpleChained<int>("refFld.someStruct.intFld");
IPtr ref = ptr.GetRefChained("refFld.innerRef");
```

To read collections (example of supported: `Array`, `List<T>`, `Dictionary<TKey,TValue>`, `ConcurrentDictionary<TKey, TValue>`) I created the specialized wrappers. API usage example:

```
List<int> listOfInts = ptr.AsCollection().List()/*Wrapper is returned. I can get elements, size, etc.*/.Read<int>();
List<KeyValuePair<int, IPtr>> dictionary = ptr.AsCollection().Dictionary().Read<int, IPtr>(); //For Dictionary<int, object>
```

To read complex values:

```
DateTime dateTime = ptr.GetThisComplexValue().DateTime();
Guid guid = ptr.GetThisComplexValue().GuidValue();
```

@JeffCyr comments:
I like the idea of making extensible convertions. However, I prefer an approach where you don't have to specify the type of the field you are accessing or whether it's interior or not. It can be resolved quickly by inspecting the ClrInstanceField without much performance hit.

e.g.

``` c#
ClrObject o = ...;
int value = o["fieldName"]["innerField"]["intField"].AsInt32();
```

``` c#
ClrObject array = ...;

foreach(ClrObject o in array)
{
    Console.WriteLine(o.Dynamic.fieldName.innerField.intField);
}
```

@Zvirja comments:
1. **Interior flag** Great catch! Yes, you are right. We can understand whether it's interior or not by inspecting the current object type (structure or reference type). Likely, I missed that point some time ago. We should check how it works for the boxed structures thought...
1. **Getting of the single field** This is where I prefer to have extension method for each simple type. I like the `o.GetInt("intField")` syntax much more than `(int)o["intFIeld'])` or `o["intField"].AsInt32()`. That will allow to better follow the extension idea and to better handle the ambiguous situations (e.g. how to return string - as object wrapper, or by value). Also will allow us to get rid of redundant boxes (when you return `int` as `object` to unbox it later.) For large heaps that could be crucial.
2. **Getting of the chain** This is the place whether we could get benefit from rather dynamic model or the indexers suggested above: o["fieldName"]["innerField"]["intField"]. They don't differ too much by idea, but we have to make API consistent and clearly document what `o["fld"]` returns in any case. I hate current `var obj = field.GetValue(address)` model when you don't know what to expect as output.
3. **Enumeration of the array** For this case we can implement enumerator. However, iarray could contain `refs`, `structs` and `primitive`. I don't like idea of implicit casts, when you write `foreach(ClrObject o in array)` in one case and `foreach(int i in array)`. At least it will lead to boxes/unboxes. However, if you have nice idea how to implement this - let's discuss. E.g. we could mitigate this with getter for generic enumerator..
4. **Enumeration of the advanced containers.** I'd use the `IEnumerable` implementation for the arrays only and do not introduce that for the advanced collections like lists and dictionaries. That will make API very heavy and you will stop to understand what is returned. I like my way with extensions better for this situations `var list = ob.AsCollection().List(); var size = list.Count; var elems = list.Read<int>()`.

**Comment by leculver** [comment]
Personally I don't like the o["field"]["field2"] syntax.  It's certainly terse (which is nice), but it looks too ugly.

Here is my general thinking:

1.  I would like to define ClrObject to represent a strongly typed object instance in the target runtime.  You can enumerate them with ClrHeap.EnumerateObjects or ClrHeap.EnumerateClrObjects.
2.  This solution should implement both a static solution for computational efficiency and also support the dynamic keyword for ease of use.
3.  ClrObject should be able to enumerate or convert arrays, but I do not think ClrMD itself should support more complex collections such as List, Dictionary, HashSet, etc.  There's simply too many to support.  I'd hope this could be solved with an extension library outside of ClrMD.
4.  However I do think we should provide conversions to a limited set of commonly used types to ensure people do not have to duplicate this code over and over.  (For example, Guid, DateTime, TimeSpan, and similar.)
5.  ClrObject needs to be defined as a struct to ensure we do not create lots of garbage when enumerating the entire heap.

Here is the rough idea I was thinking:  https://gist.github.com/leculver/2252976329e24a433da4

Usage would look like:

    foreach (ClrObject obj in heap.EnumerateObjects())
    {
        if (obj.Type != typeInQuestion)
            continue;

        // Best ways to use this
        int i = obj.GetField("fieldName").GetField("innerField").GetField<int>("intField");

        // This also works, but inefficient
        int j = obj.GetField("fieldName").GetField("innerField").GetField("intField").AsInt32();

        // Dynamic works fine too, but slower.
        int k = obj.Dynamic.fieldName.innerField.intField;

        // Enumerating primitive arrays
        int[] array = obj.GetField("_someIntArray").AsArray();
        foreach (int i in obj.GetField("_someIntArray").EnumerateArrayValues())
        {
        }
                
        // Enumerating object arrays
        foreach (ClrObject o in obj.GetField("_someObjectArray").EnumerateArrayObjectValues())
        {
        }
    }

I'm interested in thoughts and feedback.

**Comment by tomasr** [comment]
Looks like a great place to start! A few things I'd like to see (just a raw brain dump at this time).

For basic type conversions, this one is definitely welcomed! At the very least, `Guid`, `DateTime` (`DateTimeOffset`?), `TimeSpan`, and `Decimal` would be a good start.

I'm not a big fan of filling `ClrObject` with conversion routines (`AsDateTime()` and so on). Could we define those as extension methods and establish a convention for extending those? That would be, I think, far more interesting as people need to add more cases.

About `GetObjectAddress()`.... would this be equivalent to `ReadPointer(GetFieldAddress(name))`?

Another useful addition would be an `AsBaseType()` method. Basically just return `new ClrObject(Address, Type.BaseType)`. This is useful when dealing with types that have fields with the same name as a field in the base type.

For array enumeration, I'm not a bit fan of converting to an array, as it leads to too many rules for dealing with potentially large arrays in client code. This could be an extension method, as well, I think. We also need a property to represent the array length, and the option to enumerate the array an `IEnumerable<ClrObject>` instead of a typed primitive value or `IEnumerable<ulong>`.

**Comment by JeffCyr** [comment]
That is great,

Some thoughts:

#####  GetInt32Field vs GetField<T>
The specific methods would be more auto-complete friendly

##### Arrays
I agree with @tomasr, conversion to array could be harmful. I suggest creating `struct ClrArray` with the same field as ClrObject, conversion would be a simple field copy. The struct could be `IEnumerable<ClrObject>` and have an indexed property for direct element access.

**Comment by Zvirja** [comment]
Hi @leculver,

Great prototype! Here are my notes (here and later `obj` means the `ClrObject` entity):

1. __Interior__ I've just verified that boxed `structs` have the same `MethodTable` as their non-boxed counterparts (as I expected). It means that for the given `obj` there is no _easy_ way to determine whether current entity is actually object or structure. Of course, we could read the first word, pointer by address, but that is a crazy solution. Therefore, we should pass resolve this information in constructor. I suggest to store it as a bit in the `_address` field.

1. `struct` vs `class` I understand the reasons behind decision to use structures - that is amount of entities in the heap. But, I've already faced some inconveniences or drawbacks with `structs`:
  * Size for x64 is 2 words, so it doesn't fit a single register. It means that value is always passed on stack, doing the deep copying. Likely, that could degrade performance if object is passed to inner methods actively. Of course, that could be mitigated by the `ref` keyword when that is possible, but it looks like a hack more.
  * Reporting of the empty results in custom code. That is not possible to return `null` in custom code, rather we should return `ClrObject?`, follow `bool Try(out result)` convention or throw exception. The first way means that we copy 3 words (is even worse and looks ugly). The second approach makes code ugly. The third approach could not meet the philosophy that exception means error and expected failure (e.g. when something is null) should be reported in the different way.
  * The point above becomes worse because we would like to have extension methods to implement the basic logic (which is great from extensibility perspective). That means that we'll do that copying for each extension invocation.
  * We are forced to expose direct structure, rather than interface. That will force us to make all our extensions strongly typed. Otherwise, we'll get boxing on each `struct => interface` cast.

1. __Null support__ If we decide to use `struct`, there is nothing to discuss here. If we decide to use `class`, we should never return `null` for the `null` objects.

1. __ClrObject contract__. Here I would like to suggest code contract for the `ClrObject` class.
  1. Should _always_ contain non-null `Type` for non-null references. Type is always `null` for the `null reference` (for null we cannot resolve the actual type, the expected one only. That makes `obj.Type` API very ambiguous).
  1. It isn't allowed to initialize object with predefined type for _reference types_ (including boxed `structs`). Rather, type should be always resolved using the object's MT. That will ensure us that we never need to re-evaluate type, because actual type is `string`, rather than `object` that we passed to constructor.
  1. (continuation of the previous point). Structure `obj` should be always initialized with known non-null type.
  1. `ClrObject` should always keep reference to the underlying `ClrHeap`, even for the `null reference`. That means that we should store rather `Type` or `Heap` pointer, depending on whether this is null or not (to save space). Later, property `getter` should do the right cast.
  1. _Suggestion_ I'd suggest to keep the `ClrObject`clean of any logic related to fields operation. All the fields related logic should be moved to standalone extensions.
  1. I'd suggest to not provide any special native support for boxed primitive types (or do that by extensions only). Therefore, it's `ClrObject` could be returned for primitive field only if customer decide to manually get field as a structure, rather than a primitive. All other field API will return direct value.

1. __Field value readers__ I'd suggest to extend `ClrObject` with extensions only. That will make further support much simpler and will allow to group functionality. If you later decide to change container - it should be simpler to migrate.
  * __Generic reader__. I'd suggest to not implement `GetField<T>` API, because it requires boxing for primitive types - that is not great from performance perspective.

I've forked your gist and made a draft per my notes: (https://gist.github.com/Zvirja/678ce4338f81b93b3a97)[https://gist.github.com/Zvirja/678ce4338f81b93b3a97]

P.S. I'll comment other points a bit later.

Please review my points in the meanwhile, comment them and update your GIST prototype if you decide to import particular aspect from my example.

**Comment by Zvirja** [comment]
@leculver Could you please create a wiki page for that specifications? I'll describe all my thoughts there and later we will be able to modify it together. It will be much simpler than track comments.

P.S. Let me know if you see that I'm making to much noise regarding such a simple thing.

**Comment by leculver** [comment]
@tomasr / @JeffCyr:  Good points, we'll avoid converting directly to array, and I do like the idea of ClrArray as a copyable struct for array operations.

@Zvirja, I don't have access to create a wiki on this project.  I've asked one of the people who can to see what they can do.

1.  Yep, there's no getting around tracking if it's an interior pointer or not.  I planned to steal the upper bit of _address for it.
2.  Copying the structure around is a concern, and slower than a simple reference copy, but I still feel all of these concerns are outweighed by the fact that if we don't use a struct, then heap enumeration is going to kill performance when we generate that much garbage.  I've asked a performance expert on my team to weigh in when he has time (before the result is finalized), but I'm pretty sure the answer will be the same.
3.  I'm not sure I agree on this one since the the new ?. operator in C# makes traversing a list of potentially null results straigthforward  `ClrObject objField = obj?.GetField("fieldName")?.GetField("innerField")?.GetField("objField")` seems ok.
4.  See below:

> Should always contain non-null Type for non-null references. Type is always null for the null reference (for null we cannot resolve the actual type, the expected one only. That makes obj.Type API very ambiguous).

I agree in principle, but I worry this isn't pay-for-play.  Let me think of a good way to dig into this (sorry it would take a lot to type out my exact thoughts here, but I'm trying to avoid calling heap.GetObjectType to get the exact type in any cases we don't need to).  I think if we defined these properties instead I could make it work in all cases without a performance penalty...but this solution makes working with ClrObject more difficult:

    struct ClrObject {
       ulong _address;  // One bit of this is for whether _type is an exact type or not.
       ClrType _type;  // May be exact type, or a base type.

       public ClrType Type { get; }  // returns the value of _type directly
       public ClrType ExactType {get;} // Returns the exact type of _address, slower, but ensures not a base type

In any case, good point.  I'll think about the right solution here.

> ClrObject should always keep reference to the underlying ClrHeap, even for the null reference. That means that we should store rather Type or Heap pointer, depending on whether this is null or not (to save space). Later, property getter should do the right cast.

I'm not sure the benefit outweighs the cost here.  If _type is non-null we always have a valid heap (_type.Heap).  If a null reference (_address == 0), then I do understand the benefit of having a ClrHeap around, but the constant casting _type to ClrType will be costly to performance...especially since _address = 0 will be the uncommon case, and _type will be very frequently used as a type.

Defining an explicit layout for ClrObject such that type and heap are overlayed (to avoid casting) and stealing a bit from _address would work, but I'd like to be sure the benefit outweighs the complexity of that design.

~~~

Sorry, that's all the time I have today for this...I will try to respond to other comments in this thread later in the week.

**Comment by tomasr** [comment]
@leculver FWIW, I'm perfectly OK with `ClrObject` being a struct. It makes it easier to implement filtering on heap objects using regular LINQ expressions / commands on the resulting `IEnumerable<ClrObject>` rather than having to provide custom lambda expressions to minimize allocations (this suddenly becomes very important when you're dealing with 50+ million objects on the heap!)

We should also consider providing enumeration methods for `ClrObject` everywhere else we expose object addresses, such as with `EnumerateFinalizerQueue()`, `EnumerateFinalizableObjects()`, `ClrThread.EnumerateStackObjects()` and so on. These could all be extension methods probably (might need a little work to make it doable, but shouldn't be a problem).

Finally, I think it would be useful if `ClrObject` exposed a property to check if it is an interior pointer, just in case you have to drop down to the core ClrType methods for some reason (hopefully we wouldn't need this if the API was very complete, but I've run into limitations with the old code and this has been a sore point!)

**Comment by Zvirja** [comment]
Thanks for the answers.

@leculver 
> operator in C# makes traversing a list of potentially null results straigthforward ClrObject objField = obj?.GetField("fieldName")?.GetField("innerField")?.GetField("objField") seems ok.

Let me comment this particular code snippet. I believe that we should fail with exception if we are unable to find field, rather than return `null` values. Also, the `GetXXXField()` method could return either: primitive (not null), ClrObject (if this is a struct) or String. Only strings can be null, so I don't see a scenario when the chain above is possible.

> think if we defined these properties instead I could make it work in all cases without a performance penalty...but this solution makes working with ClrObject more difficult.

This is the problem I faced in my project. The issue is that `ClrObject` is immutable, so there is no way to update value - we have to add a sort of `obj.ResolveDynamicType()` API that returns a new `ClrObject` object with re-calculated type. That complicates the API significantly and you always should keep in mind that sometimes field lookup could fail just because current type is not the actual one.

>Defining an explicit layout for ClrObject such that type and heap are overlayed (to avoid casting) and stealing a bit from _address would work, but I'd like to be sure the benefit outweighs the complexity of that design.

I agree that way with cast is not great, so if you see better way - that's cool. However, I believe that such kind of agreement should be definitely present. Just imagine that you read some data and pass is to another scope for processing. If that scope could always resolve ClrHeap from the passed object, you will never have to provide it with heap object explicitly. Otherwise, you should always pass link as a backup, which messy to follow.

Also, very often, there is no exact static variable where the ClrHeap is stored - everything is passed as context (to better cover testing). Absence of ClrHeap presence guarantee would force to make that cross-call contexts more heavy :( I've already tried approach with not-null ClrHeap and found that it makes application code much clearer.

Also please let me know when you are done with Wiki - I'll move post from my Wiki to yours.

@tomasr 
>Finally, I think it would be useful if ClrObject exposed a property to check if it is an interior pointer, just in case you have to drop down to the core ClrType methods for some reason

I believe that this flag should always be present at least for the internal ClrObject needs - fields reading. Without this flag we would be unable to read values correctly.

>hopefully we wouldn't need this if the API was very complete
I vote to keep the existing API as well as it provides better performance that new API. That is especially important when you would like to read fields from a large set of the same objects. Cached `ClrFieldInstance` and object address substitution will offer you better performance than getting field from wrapper - you will have to resolve the `ClrInstanceField` for each time.

**Comment by JeffCyr** [comment]
##### Class vs Struct
I think the general rule of thumb is that struct performs better than class for size <= 16 bytes. Since ClrObject would be 16 bytes (in x64), struct should perform better.

##### Null ClrType
What would you think of the Null Object pattern for ClrType? There could be `class NullType : ClrType` for null reference and `class InvalidType : ClrType` for invalid object address. Those sub types could return default values or throw exception in their implementation depending on what makes sense.

The benefits would be that you would still be able to access the ClrHeap from a null object and queries accessing ClrObject.Type would not have to check for null.

**Comment by Zvirja** [comment]
@JeffCyr 
>What would you think of the Null Object pattern for ClrType? There could be class NullType : ClrType for null reference and class InvalidType : ClrType for invalid object address.
>....
>The benefits would be that you would still be able to access the ClrHeap from a null object and queries accessing ClrObject.Type would not have to check for null.

Great! Like it very much! It's a pretty simple idea - why haven't I invented myself? :(

**Comment by Zvirja** [comment]
@JeffCyr 
>class InvalidType : ClrType for invalid object address.

By the way, what do you mean by the invalid object address? Could you provide a couple of examples?

**Comment by leculver** [comment]
@Zvirja 

>>class InvalidType : ClrType for invalid object address.
>
>By the way, what do you mean by the invalid object address? Could you provide a couple of examples?

When inspecting a process or crash dump, you may encounter a corrupted heap, or simply inconsistent state...  The latter being that even though the heap isn't corrupted, the runtime or GC might be in the middle of updating data structures as you stopped the process in the debugger...leading to debugging APIs not being able to correctly make sense of the state of the process.  Heap corruption is (relatively) common, inconsistent state is VERY rare to find but it happens.

In practice, this would be what inconsistent runtime state manifests itself as:

    foreach (ulong obj in heap.EnumerateObjectAddresses())
    {
        ClrType type = heap.GetObjectType(obj);
    
        // This is only hit in heap corruption or inconsistent state...
        // you should always perform this check
        if (type == null) continue;
    }

**Comment by Zvirja** [comment]
Great, thanks.

In this case, likely, we have to add one more flag to the `ClrObject`.. Something like `IsInvalid` with appropriate description. This is something new to me, but now I understand that indeed, that could happen.

**Comment by leculver** [comment]
Here are some more thoughts after looking over the feedback:

1.  The InvalidType concept is a good one, and resolves some issues here.  ClrObject._type will always have a value in this case, and we can always get at the heap.
2.  Specialized ClrArray types is the right approach, and well as not having a direct "ToArray" that creates a real in-memory array.  I think there will be three array types: ClrObjectArray, ClrStructArray, ClrArray<T> (the latter for primitive types only).
3.  I think primitive and array converters (AsInt, AsArray, etc) should be in the class itself, but I agree that extra converters (AsDateTime, AsGuid, etc), should go into extension methods, hidden behind a namespace.
4.  After discussing it internally, I still strongly feel ClrObject should be a struct.
5.  I still have open questions on how the API should behave, see TODO comments.
6.  Fields which are null still return a valid ClrObject, but Address == null, and IsNull is true.  One quirk right now is that if you read a struct value from a null ClrObject, it returns a ClrObject pointing at a struct which also returns IsNull == true.  I'm not sure that's the best behavior.
7.  What should the behavior be when you get an integer field from a null ClrObject?  Right now it's an exception, but it means this code would throw if the someObj field was null:  `int i = obj.GetReferenceField("someObj").GetInt32("i")`.  Suggestions?

Here is an updated gist of what I'm thinking:  https://gist.github.com/leculver/2252976329e24a433da4

**Comment by jazzdelightsme** [comment]
7. Yes, I think it should throw.

**Comment by JeffCyr** [comment]
What do you think if there is only one `ClrObject GetField(string name)` method that works with class, stuct and primitive types? It would simplify the usage and I don't see a performance hit.

In the same line of thought, there could only be one ClrArray class instead of ClrObjectArray/ClrStructArray.

```c#
public ClrObject GetField(string fieldName)
{
    ClrInstanceField field = _type.GetFieldByName(fieldName);
    if (field == null && !IsTypeExact)
        field = Type.GetFieldByName(fieldName);

    if (field == null)
        throw new InvalidOperationException(string.Format("Field '{0}' not found in type '{1}'.", fieldName, _type.Name));

    ClrType fieldType = field.Type;
    ulong fieldAddress = field.GetAddress(Address, IsInterior);
    ulong objectAddress;
    bool isTypeExact;

    if (fieldType.IsObjectReference)
    {
        Heap.ReadPointer(fieldAddress, out objectAddress);
        isTypeExact = fieldType.IsSealed;

        // The exact type could be resolved here if we want
        //if (!isTypeExact && fieldAddress != 0)
        //{
        //    fieldType = Heap.GetObjectType(fieldAddress) ?? InvalidType.Instance;
        //    isTypeExact = true;
        //}
    }
    else if (fieldType.IsPrimitive || fieldType.IsValueClass)
    {
        objectAddress = fieldAddress;
        isTypeExact = true;
    }
    else
    {
        throw new NotSupportedException(string.Format("Object type not supported '{0}'", fieldType.Name));
    }

    return new ClrObject(objectAddress, fieldType, isTypeExact, !fieldType.IsObjectReference);
}
```

##### o.GetInt32Field("foo") vs o.GetField("foo").AsInt32()
Concerning the specific GetXXXField methods, am I missing something because I see them more as api sugar than a performance benefit. The latter does a bit more checks, but not that much and there's no allocation, I don't expect it to be the bottleneck in a large dump investigation.

##### Lazy exact type
Is it that expensive to always get the exact type when creating a ClrObject? Most of the ClrObject creation will come from ClrHeap.EnumerateClrObjects where we must get the exact type anyway. When creating a ClrObject from an inner field, the only case we can't rely on the field type is for not sealed class. It would simplify the implementation to assume it's the exact type (or base type if AsBaseType() is called).

**Comment by JeffCyr** [comment]
@leculver It can be annoyant, but I agree with @jazzdelightsme I think the most natural/intuitive behavior is to throw an exception on GetField and GetXXXField if the field is missing or the object is null.

**Comment by JeffCyr** [comment]
##### Extensible conversions
Creating custom extension method works fine when using ClrObject, but it may pose a problem when using the dynamic accessor.

An approach could be to register custom conversion somewhere in a static class and to use them automatically in a generic `ClrObject.As<T>` method and DynamicObject.TryConvert

**Comment by tomasr** [comment]
>An approach could be to register custom conversion somewhere in a static class and to use them automatically in a generic `ClrObject.Convert<T>` method and DynamicObject.TryConvert

You can already invoke extension methods like regular static methods, so what would be the point?

**Comment by JeffCyr** [comment]
@tomasr Yeah it's true, we could keep the AsXXX static methods instead of a generic `ClrObject.Convert<T>`. The AsXXX methods would be more discoverable to know if a conversion exists.

Here's a more detailed explanation of my concern. If I create a custom converter for type `MyClass`, I expect it to work when I do 
```c#
ClrObject o = ...;
MyClass myClass = (MyClass)o.Dynamic.field1.field2;
```

This won't work automatically if my custom converter is an extension method on ClrObject, the DynamicObject doesn't know about it.

We could register the converter with something like this:
```c#
public static class ClrObjectConverters
{
    public static void RegisterConverters()
    {
        ClrDynamicObject.RegisterConverter(o => o.AsMyClass());
    }

    public static MyClass AsMyClass(this ClrObject o)
    {
        return ...;
    }
}
```

**Comment by leculver** [comment]
@JeffCyr

> I think the most natural/intuitive behavior is to throw an exception on GetField and GetXXXField if the field is missing or the object is null.

Agreed.

> Is it that expensive to always get the exact type when creating a ClrObject?

ClrHeap.EnumerateObjects already finds the exact ClrType, so you are right that particular case won't be expensive.  However, when dealing with fields, it will be costly.  That's because it's always expensive to read memory from the target process (walking the heap is OK because we batch up the reads).

Something like `int i = (int)o.Dynamic.field1.field.i2;` could hit the case where we have to look up the concrete types.  Let's say field1 and field2 are defined as "object".  When we construct ClrObject after getting field1, its ClrType will be of System.Object.  When we go to get field2, we won't find it in System.Object...so we'll have to get the concrete type.

See `GetObjectField` method in this gist: https://gist.github.com/leculver/2252976329e24a433da4.  We call GetFieldByName twice in that method.  Once on _type (whatever we were given as the type) and then once on Type (which resolves the real type).  Also if the user (for any reason) calls Type on a ClrObject we got from a field we will have to resolve the concrete type.

All of this still seems like the right design though, even if it is a little costly in some cases.  I'm just thinking through the implications out loud, so to speak.

> This won't work automatically if my custom converter is an extension method on ClrObject, the DynamicObject doesn't know about it.

Ah, I get it now.  RegisterConverter may be the right solution, but I'll put more thought into it when I actually start designing these classes.

**Comment by JeffCyr** [comment]
@leculver Alright, I guess it's a free optimization for most usage. However since the struct becomes mutable with the lazy exact type, it becomes easy with linq queries to set the exact type on a copy of the struct multiple times on different copies and perform even more exact type fetching.

Maybe the lazy exact type is still the correct trade-off, it's just something to be aware though.

**Comment by leculver** [comment]
Yep, that's also a concern.  I don't know what the right tradeoff is right now, but I also haven't sat down to really design it and think through everything.  This issue was a good brainstorming session, and I'll see where it lands.  The Linq case is a compelling one...though I'd envisioned that most linq queries would be primarily running through the heap (which has exact types), and less through fields (which may have inexact types).

In either case, this is on hold for a bit longer.  I want to push out a build this week to NuGet before doing any big feature work.

**Comment by leculver** [comment]
I have a pull request open here which has a basic implementation:  https://github.com/Microsoft/clrmd/pull/30

I do not intended to merge this PR until next weekend if there are any comments on the code or design.  Please do not consider any of this finalized until it goes into the master branch and I've shipped a NuGet package containing it.

**Comment by kevingosse** [comment]
Are you still considering adding `dynamic` support to ClrMD?

I developed a set of extensions to use dynamic with ClrMD a while ago, not knowing about your pull request: https://github.com/kevingosse/DynaMD

Depending on what your plans are, I wonder if it would make sense to stop maintaining DynaMD and add the features directly to `ClrObject`

**Comment by leculver** [comment]
@kevingosse  I'm not planning to add it anymore.  I've been meaning to kill the branch and PR, but I haven't gotten around to doing so.  An extension library exposing the functionality is much better place for that kind of code to live, so feel free to publish your extensions to NuGet.  =)
