### ISSUE TITLE
ClrMD memory leak Thread.BlockingObjects

### ISSUE THREAD

**Issue by DarkWalker** [Microsoft/clrmd#3]
The code:

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading;
using Microsoft.Diagnostics.Runtime;

namespace ConsoleApplication1
{
    internal class MyClass
    {
        public static void Main()
        {
            var thread = new Thread(
                () =>
                {
                    while (true)
                    {
                        Console.WriteLine("123");
                    }
                });

            thread.Start();

            var pid = Process.GetCurrentProcess().Id;

            using (var dataTarget = DataTarget.AttachToProcess(pid, 5000, AttachFlag.Passive))
            {
                string dacLocation = dataTarget.ClrVersions[0].TryGetDacLocation();
                var runtime = dataTarget.CreateRuntime(dacLocation);

                while (true)
                {
                    Thread.Sleep(200);


                    foreach (var t in runtime.Threads)
                    {
                        var temp = t.BlockingObjects;
                    }

                    runtime.Flush();

                    GC.Collect();
                }
            }
        }
    }
}
```

When you run this code managed memory stays consitent, but native memory grows consistently. The detalization of most memory allocations below:
![clrmd_memoryleak](https://cloud.githubusercontent.com/assets/1113773/7231011/2515a900-e77b-11e4-9168-2efe970b5915.png)

In my test run I got from 2.2 MB to 10.5 MB in 8 minutes, so I guess it is easily reproducible.

Original discussion is here: https://github.com/Microsoft/dotnetsamples/issues/19

_Upd1_: in order to run code in 4.6 use this version https://github.com/Microsoft/dotnetsamples/issues/11
_Upd2_: Some of memory leak is due to: https://github.com/dotnet/coreclr/issues/1379, but probably this is not all of them.

**Comment by weltkante** [comment]
> Upd1: in order to run code in 4.6 use this version Microsoft/dotnetsamples#11

My workaround should no longer be needed, they have a [proper version check](https://github.com/Microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/datatargetimpl.cs#L152) now. If you have any problems its something different than the linked issue.

**Comment by leculver** [comment]
I took a look.  This seems like a memory leak in the underlying dac API.  I let your repro program "warm up" a bit, then snapped two crash dumps just after the GC.Collect with a few minutes of runtime between them.  Here's what I see:

  User time: 0 days 0:04:37.000
--- Usage Summary ---------------- RgnCount ----------- Total Size -------- %ofBusy %ofTotal
Free                                     98          71d8b000 (   1.779 GB)           88.95%
Image                                   401           6267000 (  98.402 MB)  43.46%    4.80%
<unknown>                               165           455f000 (  69.371 MB)  30.64%    3.39%
Heap                                    360           3152000 (  49.320 MB)  21.79%    2.41%


  User time: 0 days 0:06:05.000
--- Usage Summary ---------------- RgnCount ----------- Total Size -------- %ofBusy %ofTotal
Free                                    100          70da6000 (   1.763 GB)           88.17%
Image                                   412           6267000 (  98.402 MB)  40.61%    4.80%
<unknown>                               168           4575000 (  69.457 MB)  28.67%    3.39%
Heap                                    466           4121000 (  65.129 MB)  26.88%    3.18%

So it looks like the heap is growing a little each time.  I used the following code to look at CLR's heaps in both crash dumps, but it turns out they are exactly the same (so the issue doesn't live in ClrMD, but in the dac).

    // This reports the same for both crash dumps.
    var segments = from s in runtime.EnumerateMemoryRegions()
                    group s by s.Type into g
                    let size = g.Sum(p => (long)p.Size)
                    orderby size descending
                    select new
                    {
                        Region = g.Key,
                        Size = size,
                        Count = g.Count(),
                        Items = g
                    };

Sometime this week I'll put the issue under UMDH and see where the native side is leaking memory.  We may be able to fix the issue in future versions of CLR, but unfortunately fixing bugs in the dac for already shipped CLRs is very difficult (and costly) to do.  Here is what I'm adding to the documentation about this:

"Please understand that ClrMD is built on top of an older API which is rarely updated (though we do fix bugs in new releases).  While we can easily update ClrMD itself, there are cases where there known issues in older versions of the runtime itself, which we cannot easily fix.  Generally speaking, we can fix bugs in future shipping versions of CLR, but older versions we have already shipped it's is EXTREMELY diffcult (and unlikely) that we will port fixes back to older runtimes.

This is especially true for memory leaks in the diagnostic APIs that ClrMD uses.  If you suspect a memory leak or other issue, please do report it, as hopefully we can fix it for future versions of Clr.  For already shipped versions of Clr, you should expect (minor) memory leaks and other issues that we will not go back and fix."

**Comment by leculver** [comment]
With the changes made to the upcoming ClrMD 1.0 I've done all I can to ensure memory is released properly in the dac interfaces.  Unfortunately if there's more hiding behind the scenes it's going to be a bug in the runtime itself.  Please feel free to refile a new bug if you feel something is leaking on ClrMD 1.0, but it's likely that any problems there are actually in the runtime itself and not ClrMD.
