### ISSUE TITLE
Support Linux core dump "module metadata mapping fix" 

### ISSUE THREAD

**Issue by sdmaclea** [microsoft/clrmd#308]
@mikem8361 said:
Core dumps are missing all or some of the metadata in the assemblies.  On Windows, dbgeng “maps” the modules into the address space automatically when SOS or CLRMD reads the metadata blob in the module.  I added something similar to SOS on Linux because lldb doesn’t do this. I also had to adding this module mapping to dotnet-dump on Windows too. I don’t think CLRMD supplies a ICLRMetadataLocator interface on the data target it passes to the DAC which is one way for debuggers, etc. to supply the DAC with the missing metadata. SOS for Linux under lldb and dotnet-dump do this at a lower level by detected that a failed memory read is in an assembly’s metadata blob and then downloads the assembly and “maps” it into the address space.
 
mikem

Mike is adding a fix for this into dotnet-dump. It feels like we need support at the ClrMD level. See https://github.com/mikem8361/diagnostics/commit/78c88d11effa7ef5237e28b6ec26f4fb784aa209

/cc @leculver @mikem8361

**Comment by leculver** [comment]
> I don’t think CLRMD supplies a ICLRMetadataLocator interface on the data target it passes to the DAC which is one way for debuggers, etc. to supply the DAC with the missing metadata.
We do actually, here's the code in ClrMD:

https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs#L265-L276

In the repro we discussed offline, I can see that `GetMetadata) is being called and we do return S_OK, but there's still something wrong with the result.  I will get back to debugging the issue on Tuesday.

**Comment by leculver** [comment]
Ah the underlying issue here is that we don't properly set FileSize and TimeStamp on Linux modules here:  https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/DataReaders/Core/CoreDumpReader.cs#L106

Which means when we attempt to locate the module during ReadVirtual, we fail here:  https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/DacInterface/DacDataTargetWrapper.cs#L166

The fix should be just to properly fill in the FileSize/TimeStamp module information for PEImages in the module list.

**Comment by leculver** [comment]
Fixed by https://github.com/microsoft/clrmd/pull/310.
