### ISSUE TITLE
ClrmdHeap._memoryReader leak

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#409]
`ClrmdHeap._memoryReader` won't be reset to `null` unless the enumeration is completed.

https://github.com/microsoft/clrmd/blob/80471484a9b0abcffe37096416346e9e8981858c/src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs#L31

https://github.com/microsoft/clrmd/blob/80471484a9b0abcffe37096416346e9e8981858c/src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs#L306

For example,

https://github.com/microsoft/clrmd/blob/80471484a9b0abcffe37096416346e9e8981858c/src/Microsoft.Diagnostics.Runtime.Tests/src/TypeTests.cs#L110

**Comment by leculver** [comment]
Yeah the whole implementation of `MemoryReader` doesn't make a lot of sense if we allow multithreading in general.  Thanks for filing the issue, it's a good reminder to get back around to this.  At its core, MemoryReader was _trying_ to solve two problems:

1.  When enumerating the heap, reading the data target object by object is very slow.  We want to read the heap in large chunks and operate on those chunks.
2.  When enumerating the heap, we may want to enumerate object references, so it makes sense to read those object references out of the pre-fetched memory if we have it available.

I'll probably scrap `MemoryReader` and come up with a better design to accomplish this.  I'll take a look soon.

**Comment by leculver** [comment]
I put in a spot fix for this.  I think long term I need to build a synchronized LRU cache of segments of memory in the gc heap.  This would let object reference enumeration much more efficient when running something as slow as the GCRoot algorithm.

However, that's all just optimization and there's a ton of other stuff to go fix that's not working, so that's a problem for another day.
