### ISSUE TITLE
Array pool leak in enumerable methods

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#441]
Similar to #409 

The array won't be returned to pool unless the enumeration is completed.

https://github.com/microsoft/clrmd/blob/5f44a5c9a08fb4fe6237a111cb0a1eae748d112a/src/Microsoft.Diagnostics.Runtime/src/Implementation/ClrmdHeap.cs#L217

**Comment by leculver** [comment]
This is ok.  ArrayPool usage here is a best-effort to not thrash the heap by constantly allocating, it's not a bug if we can't return the array in 100% of cases.  ArrayPool will happily keep allocating for us, and I would imagine the normal case is to finish the enumeration anyway.

The main reason I fixed #409 is because using the thread static meant we could end up truly "leaking" the memory in the MemoryReader case if the user kept the thread around but never re-called EnumerateObjects we'd never clean it up.
