### ISSUE TITLE
Problem about module's name

### ISSUE THREAD

**Issue by ZQiu233** [microsoft/clrmd#529]
ClrModule has 3 properties about name:
1.Name
2.FileName
3.AssemblyName
But it seems that they three return the same name.
If the assembly is loaded from byte[],then the three name return the full name of the assembly.
If the assembly is loaded from a .dll or .exe file,then the three name return the path of it.

Why this happend?I think at least "AssemblyName" should not be the path of an assembly.
Is it going on a wrong way?Or I'm wrong?

**Comment by NextTurn** [comment]
`FileName` is `null` for dynamic modules (generated by `System.Reflection.Emit`).

`AssemblyName` and `Name` are usually identical since most assemblies only contain a single module with the same name.

**Comment by ZQiu233** [comment]
> `FileName` is `null` for dynamic modules (generated by `System.Reflection.Emit`).
> 
> `AssemblyName` and `Name` are usually identical since most assemblies only contain a single module with the same name.

Got it.But how to get the full name of the assembly though.

**Comment by NextTurn** [comment]
> Got it.But how to get the full name of the assembly though.

That could be available through a new `ClrAssembly` class, but I'm not sure if there are many use cases around it. @leculver

**Comment by leculver** [comment]
I'm fine with adding a ClrAssembly class.  I was planning to do this for ClrMD 2.0 but the cases where the assembly is the module is _relatively_ rare and it's much more convenient to not have to go through another level of indirection.  It's true that the current implementation is likely not were we want to be.

Thanks for filing this issue.  This is something I want to tackle before we ship ClrMD 2.0 RTM.

**Comment by NextTurn** [comment]
@leculver It seems a bit weird that `ClrModule.Name` returns the full path of PE file. It doesn't reflect the module's real name specified in *ModuleDef*.

I think it should instead return a short name which looks like the file name (with path removed).

**Comment by leculver** [comment]
We are a bit hamstrung on how we report module "names" by the APIs that are provided by the dac.  I've cleaned this up somewhat, but Name and AssemblyName will continue to report filenames, because it's what the CLR diagnostics layer is reporting to us.  Essentially [GetPEFileName](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/debug/daccess/request.cpp#L2047) doesn't _really_ give us a PEImage filename in all cases.  I suppose in a perfect world "name" would be the raw name in metadata as NextTurn suggests, but honestly I don't want to go digging through metadata (which might not be in crash dumps).

In the end, I've simplified this down to two things:

- `ClrModule.Name` - _Usually_ a filename, sometimes a display name.
- `ClrModule.AssemblyName` - _Usually_ the same as `Name`, but if the module belongs to a multimodule assembly then it will be the name of the assembly (this is for desktop CLR only, I don't think coreclr has multimodule assemblies).
