### ISSUE TITLE
Early exit for corrupted PE images resources?

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#564]
When experimenting with my own version of *createdump* on x86, the number of resource entries were unreasonably large (over thousands) but we were unable to detect this error.

https://github.com/microsoft/clrmd/blob/69db395bbcc3db1fbdb7bfa0bad31cafebbe72ea/src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/ResourceEntry.cs#L130

A known problem is that we didn't check if `PEImage.Read<T>` returned a valid result.

https://github.com/microsoft/clrmd/blob/69db395bbcc3db1fbdb7bfa0bad31cafebbe72ea/src/Microsoft.Diagnostics.Runtime/src/Utilities/PEImage/PEImage.cs#L382

**Comment by swift-kim** [comment]
I also have this issue on my machine (Tizen armel). Printing a simple stack trace of an application (which normally has 40+ dlls loaded in memory) took `1m43.092s` for a minidump and `0m13.167s` for a minidump with heap.
```
count = 18328 + 63042
count = 0 + 0
count = 37500 + 58526
count = 0 + 1
count = 0 + 1
...
```

**Comment by mikem8361** [comment]
I have also noticed a problem like this in dotnet-dump's `lm` command. A huge perf problem that affects the first command run because the modules are enumerated to find the runtime module. Getting the Version for each PE image in the Linux core dump was taking way too long and failing.  

The problem is the "layout" of managed PE modules. Some PE's are "file" layout and some are "loaded" layout. The "isVirtual" flag in the PEImage constructor needs to be set based on the layout, but there is no way to determine that in the core dump data reader. If the layout/isVirtual flag is set incorrectly, PEImage doesn't enumerate through the resources correctly, takes a long time because it is reading really long garbage strings, etc.

The solution I've been working (for release/1.1 for now since that is what dotnet-dump needs), is to skip all the PE's in the ELF reader module list.  IDataReader.EnumerateModules() is meant to return just native modules (like libcoreclr.so, etc) but the PE's show up because it uses the NT_FILE entries in the coredump and because the PE's are memory mapped by the runtime as shared named memory,

I think the best fix is too skip all the PE's (modules that ELFLoadedImage.Open can't open).  The managed assemblies can be enumerated at a higher level (ClrRuntime.Modules) without any problems.  dotnet-dump has a "clrmodules" command to do that.  The only thing that needs to be added to that is displaying the module Version a customer requested feature that caused all the problems in the native IDataReader.EnumerateModules implementation.

/cc: @leculver

**Comment by leculver** [comment]
I've fixed this in PR #620.

@swift-kim It would be interesting to take a look at _why_ the those dlls don't correctly read PE image headers/resources.  #620 gives early outs so we won't spend as long failing to look up modules, but it feels like there's still an underlying bug here where we shouldn't be reading those huge counts.

If you have time to debug your scenario and take a look that'd help a lot.  If not no worries.

**Comment by leculver** [comment]
This version (and later) contains the fix:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.0-beta.20222.5

**Comment by leculver** [comment]
Ah the problem you are running into is possibly https://github.com/microsoft/clrmd/issues/475 where we are misinterpreting the layout.  I haven't tackled that issue yet.

**Comment by swift-kim** [comment]
@leculver Okay. I'll go through it after finishing some my jobs. Just note that I currently see this error with the recent changes. Maybe `ReadSections()` should return `ImmutableArray<SectionHeader>.Empty` instead of `default`.
```
sh-3.2$ dotnet stacktrace/PrintStackTrace.dll coredump-6424
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Diagnostics.Runtime.Utilities.PEImage.RvaToOffset(Int32 virtualAddress) in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Utilities\PEImage\PEImage.cs:line 191
   at Microsoft.Diagnostics.Runtime.Utilities.PEImage.CreateResourceRoot() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Utilities\PEImage\PEImage.cs:line 249
   at Microsoft.Diagnostics.Runtime.Utilities.PEImage.get_Resources() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Utilities\PEImage\PEImage.cs:line 107
   at Microsoft.Diagnostics.Runtime.Utilities.PEImage.GetFileVersionInfo() in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\Utilities\PEImage\PEImage.cs:line 223
   at Microsoft.Diagnostics.Runtime.CoreDumpReader.CreateModuleInfo(ElfLoadedImage image) in E:\public\clrmd2.0\src\Microsoft.Diagnostics.Runtime\src\DataReaders\Core\CoreDumpReader.cs:line 114
```

**Comment by leculver** [comment]
@swift-kim Sorry about that, should be fixed as part of: https://github.com/microsoft/clrmd/pull/622.

I'll push a nuget package after it's built and signed.

**Comment by leculver** [comment]
Published here, should be usable in about an hour:  https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime/2.0.0-beta.20222.8

**Comment by swift-kim** [comment]
@leculver It worked. Thanks!
