### ISSUE TITLE
Can you provide managed thread name?

### ISSUE THREAD

**Issue by karelkral** [Microsoft/clrmd#57]
I am missing analogy of Thread.Name in ClrThread.

**Comment by tomasr** [comment]
I don't think there's an easy way to get this.

The DAC requests don't provide access to `clr!THREAD::m_ExposedObject`, which would allow you to actually fetch the matching `System.Threading.Thread` object for the thread (from which you could read the `m_name` field).

**Comment by JeffCyr** [comment]
You can enumerate the `System.Threading.Thread` objects and match the `ClrThread` with the managed thread id with `m_ManagedThreadId`

**Comment by JeffCyr** [comment]
```c#
	var threadIdAndNames =
		from o in runtime.Heap.EnumerateObjects()
		where o.Type.Name == "System.Threading.Thread"
		select new
		{
			ManagedThreadId = o.GetField<int>("m_ManagedThreadId"),
			ThreadName = o.GetStringField("m_Name")
		};
```

Then you can match `ManagedThreadId` with the one in runtime.Threads to get the full thread info.

**Comment by leculver** [comment]
Sorry for the very long delay in responding.

As JeffCyr points out, this is possible to implement with the surface area provided by ClrMD, so it's not something I plan to put into the library itself.  I try to keep ClrMD down to just "building blocks", giving you the functionality to implement something like what you are describing instead of building those things directly into ClrMD.

Thank you!
