### ISSUE TITLE
API Design and Issues thread

### ISSUE THREAD

**Issue by NextTurn** [microsoft/clrmd#624]
It seems to me that "helpers" are usually some small utilities that complement the main functions, while in ClrMD the "helpers" build everything (especially the `RuntimeBuilder` which implements 10 `I*Helpers`).

**Comment by leculver** [comment]
I'm terrible at naming things.  =)

The original idea was that `Builders` actually construct Clr* types, where as `Helpers` are what various Clr* implementations use to implement its functionality.  That's not really how it's worked out in practice.

These kinds of naming issues are what I'm hoping to fix in "API Review" which I call out here:  https://github.com/microsoft/clrmd/issues/614.  Feel free to use this issue (or create new issues) for things that look weird/should be renamed in the surface area.  I want to do a full pass over the entire library on or before the date listed in 614.

(Though also I don't plan for I*Helpers and I*Builders to be a "stable" API surface.  I haven't documented that fact yet, but those are implementation details that are there in case someone wants to mock the internals of ClrMD without having to construct an entire object model.  I don't plan to support a stable version of those APIs.)

**Comment by leculver** [comment]
Fix data readers: https://github.com/microsoft/clrmd/pull/630#issuecomment-619144883

**Comment by leculver** [comment]
Fix inconsistent "Minidump" vs "MiniDump" and "Coredump" vs "CoreDump".

**Comment by NextTurn** [comment]
Clarify that `IDataReader.GetVersionInfo` only works for native modules?

**Comment by leculver** [comment]
I've mostly finished API breaking changes/fixes.  I'm trying to scope my work down to things that need to be fixed before RTM, IE breaking changes.  The I*Builder/I*Helper issue I'm leaving until a bit later since I'm not promising those interfaces will remain stable.  They are primarily meant for testing/mocking parts of the library.

Any feedback on API issues or changes within the `Microsoft.Diagnostics.Runtime` is greatly appreciated as I'm trying to ship 2.0 RTM on the 15th.

> Clarify that `IDataReader.GetVersionInfo` only works for native modules?

I'm still debating what to do about this.  Having the version information for all modules (native or managed) is super useful for tools to have.  Especially when listing out modules to the user.  Removing `ModuleInfo.Version` or making it return bogus data for managed code makes me sad. 
 File layout issues with managed code make it very difficult to do anything sensible though.

I think `IDataReader.GetVersionInfo` is the last major API issue I have planned to work on unless you or other folks raise other API concerns.  I'm not sure what I'm going to do with it yet.

**Comment by leculver** [comment]
- [ ] GetStaticFieldByName / GetInstanceFieldByName add nothing, they are simply wrappers around *Fields.FirstOrDefault.  Need to remove those unless we provide something significantly better than FirstOrDefault (like binary search, or hashset lookup, which I don't think we will do)

**Comment by NextTurn** [comment]
I propose to change `ClrEnum.EnumerateValues` to return `IEnumerable<(string Name, ulong? Value)>` instead. It's less common/useful to box integral types.

**Comment by drewnoakes** [comment]
Consider adding the Public API Analyzer. It records the public API surface area in a per-project text file, making it easy to see when PRs modify public APIs.

**Comment by leculver** [comment]
> I propose to change `ClrEnum.EnumerateValues` to return `IEnumerable<(string Name, ulong? Value)>` instead. It's less common/useful to box integral types.

That seems reasonable.  Feel free to submit a PR for that.

> Consider adding the [Public API Analyzer](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/). It records the public API surface area in a per-project text file, making it easy to see when PRs modify public APIs.

Also looks reasonable, I'll take a look at that as soon as we ship.

**Comment by leculver** [comment]
At this point I think I'm happy with the surface area, at least enough to where I'm ok shipping 2.0.

**Comment by drewnoakes** [comment]
> Consider adding the [Public API Analyzer](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/). It records the public API surface area in a per-project text file, making it easy to see when PRs modify public APIs.

Implemented in #826.
