### ISSUE TITLE
Compiling the TestTargets.proj failed

### ISSUE THREAD

**Issue by raffaeler** [microsoft/clrmd#749]
I would like to run the tests, in order to contribute to the Utilities project.
After cloning the project, I restored and built the binaries successfully, but running the test batch fails.
Other tests I did:
- compiling from VS is ok, but all the tests are failing because the dmp files cannot be found
- I run `dotnet build TestTargets.proj` to  create the artifacts (dmp files) but it also failed

```
Build started 10-Jun-20 14:45:47.
Project "H:\Samples\_forks\clrmd\src\TestTargets\TestTargets.proj" on node 1 (default targets).
BuildWindowsShared:
Skipping target "BuildWindowsShared" because all output files are up-to-date with respect to the input files.
BuildWindows:
Skipping target "BuildWindows" because all output files are up-to-date with respect to the input files.
H:\Samples\_forks\clrmd\src\TestTargets\TestTargets.proj(101,5): error MSB4062: The "Microsoft.Diagnostics.Runtime.Tests.Tasks.Dump" task could not be loaded from the assembly H:\Samples\_forks\clrmd\src\
TestTargets\..\..\artifacts\bin\TestTasks\\netcoreapp3.1\TestTasks.dll. Could not load file or assembly 'file:///H:\Samples\_forks\clrmd\artifacts\bin\TestTasks\netcoreapp3.1\TestTasks.dll' or one of its
dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public
class that implements Microsoft.Build.Framework.ITask.
Done Building Project "H:\Samples\_forks\clrmd\src\TestTargets\TestTargets.proj" (default targets) -- FAILED.
```
Hints?
TIA

**Comment by leculver** [comment]
> BTW are you interested in pull requests on the Utilities project?

Yep I accept pull requests in the utilities project, though it needs to be broadly usable by other people.

Feel free to submit any PR that you like, but if you are thinking of implementing a really large feature or pull request recommend opening an issue before you do the work to chat about the api and design.  That way if there's issues or I don't think it fits with the library then you'll know before doing a lot of work. =)

Closing this issue since the test targets project issue was resolved.  Thanks!
