### ISSUE TITLE
First-chance NullReferenceException inside ModuleInfo.GetPEImage

### ISSUE THREAD

**Issue by raffaeler** [microsoft/clrmd#754]
The following is the code found in [ModuleInfo.GetPEImage](https://github.com/microsoft/clrmd/blob/e37d17c4a4189cdf50c8432ea33a27007604b4cf/src/Microsoft.Diagnostics.Runtime/src/Common/ModuleInfo.cs#L50)
```
// ...
PEImage image = new PEImage(new ReadVirtualStream(DataTarget.DataReader, (long)ImageBase, IndexFileSize), leaveOpen: false, isVirtual: _isVirtual);
// ...
```
The problem is that `ModuleInfo.DataTarget` is null.
The generated exception is catched, but it can be definitely avoided.

**Comment by NextTurn** [comment]
Are you using `ModuleInfo`s directly from `IDataReader.EnumerateModules()`? The `DataTarget` property hasn't be initialized at that time because the data readers don't keep references to the `DataTarget`... Using `DataTarget.EnumerateModules()` can prevent this problem.

**Comment by raffaeler** [comment]
Yes this is the case, thanks
Anyway, the DataTarget property should be checked instead of throwing.

**Comment by leculver** [comment]
Thanks!  This is definitely a bug.  I will take a look at this later in the week.

**Comment by leculver** [comment]
Finally getting back around to clrmd work.  The underlying issue here is I exposed the wrong property.  `ModuleInfo` has a `DataTarget` property which should not be there.  I meant to expose an `IDataReader` parent, not `DataTarget`.  I've had to mark some of this obsolete but at minimum a build will be out this week to fix it.
