### ISSUE TITLE
Expose CLR version in ClrRuntime

### ISSUE THREAD

**Issue by tomasr** [Microsoft/clrmd#8]
When creating a `ClrRuntime` object, the user will often want to keep track of the version of the CLR that the runtime was created for. Because `ClrRuntime` doesn't expose the CLR version number, it often requires users to keep track of additional data.

It would be useful if `ClrRuntime` exposed a Version property (of type `VersionInfo`) that exposed this information directly. Exposing the complete `ClrInfo` object could be another option, but possibly too heavy-weight.

I looked at this and it does require a few changes in how `ClrRuntime` objects are created, as these do not contain the necessary information. Either we'd need to obtain it there, or another option would possibly change the `ClrRuntime` creation process so that you had to pass in the `ClrInfo` object as well, and not just the DAC location (though this would impact existing code).

This would also make it possible to easily hang interesting extension methods, such as checks for 4.5 or above, and so on (which are often very useful when analyzing code).

**Comment by leculver** [comment]
I've went the route of exposing the full ClrInfo object.  See this commit:  https://github.com/Microsoft/clrmd/commit/42ec8485da700af1dc3f037944f5b1172e74e8aa

However to use it you need to use the new startup path, which uses ClrInfo.CreateRuntime instead of DataTarget.CreateRuntime in the current branch.
