### ISSUE TITLE
Better document the "undefined" behaviour of attaching to an unsuspended process

### ISSUE THREAD

**Issue by loop-evgeny** [microsoft/clrmd#822]
The xmldoc for `DataTarget.AttachToProcess` says

> Note that if <paramref name="suspend"/> is set to false the user of ClrMD is still responsible for suspending the process itself. ClrMD does NOT support inspecting a running process and will produce undefined behavior when attempting to do so.

This is a very important use case for us - being able to attach to a running process *without* suspending it is precisely what makes ClrMd useful for getting stack traces in production, where we cannot afford to suspend the process long enough to analyse it or create a dump. In my testing this seems to work just fine. It would be great to better document what exactly this "undefined" behaviour could be, i.e. what the risks are.  For example, can it:

- crash the target process? (Really bad!)
- crash the process using ClrMd? (not so bad)
- produce stack traces that are obviously wrong? (not so bad)
- produce stack traces that are non-obviously wrong? (worse)
- miss some threads entirely?
- not even affect this use case at all?

**Comment by leculver** [comment]
> being able to attach to a running process without suspending it is precisely what makes ClrMd useful for getting stack traces in production,

Please note that ClrMD is designed to be a debugging api, not a profiling API.  This scenario is why I created the [CreateSnapshotAndAttach](https://github.com/leculver/clrmd/blob/60be1e1302c74f0c415a9e71d3b75d779936e17d/src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs#L389) entrypoint, and that's what is supported for the scenario you are referring to.

> In my testing this seems to work just fine. 

The unfortunate nature of stress/reliability bugs is that it will work just fine in 99.999% of cases, but that 0.001% will absolutely wreck production when it happens.  I agree that in the vast majority of cases everything _will_ work fine, but are you ok with a 1 in 100000 chance to wreck the production environment you are monitoring?  (Note these are made up numbers, I don't know the real risk, but I know it's not 0.)

> It would be great to better document what exactly this "undefined" behaviour could be, i.e. what the risks are.

If I could quantify what the risks actually are it might not be an unsupported feature, but I can't.  When I say undefined behavior here I really mean it.  I can give you some ideas about what ClrMD is doing and why the behavior is undefined, but I will never try to document what behaviors are expected when attaching to a running, un-suspended process because your results will widely vary.  I will say I don't think this problem has gotten any worse in 2.0 than it was in 1.1 (but I'm not sure).

Here's some hints I can give, but again **I cannot promise any given behavior when you use the library this way**:

> crash the target process? (Really bad!)

ClrMD doesn't modify the target process in any way when you use `AttachToProcess` with `suspend=false`.  We only call OpenProcess/ReadProcessMemory/GetThreadContext and similar.  Since we don't directly modify memory, it's _unlikely_ that we will cause a crash.  Performance may take a hit though, as calling GetThreadContext may suspend threads internally (I don't know), and if the dac hits an infinite loop you might starve the target process of resources which also may cause unexpected exceptions in the target process (like timeouts) which could lead to unexpected behavior.

> crash the process using ClrMd? (not so bad)

Possibly.  Worse you could end up in an infinite loop in the dac.  Meaning that try to get the property ClrRuntime.Threads and that call simply never returns.

> produce stack traces that are obviously wrong? (not so bad)
> produce stack traces that are non-obviously wrong? (worse)

Yes and yes.  The CLR stackwalker is a fickle piece of code, and a moving process could easily confuse it.

> miss some threads entirely?

Absolutely.  Threads are a linked list in the process (kinda), so when the dac/ClrMD tries to walk them you might hit a case where the target process was updating that linked list in a way that looks inconsistent to the dac.  That is, the dac doesn't respect locks in the target process which protect from reading inconsistent data.

This means sure, the dac could skip threads...or worse, loop that linked list back onto itself due to reading at an "unlucky" time, producing duplicate ClrThread objects.  Also, since most reads in the dac are cached, the second time you "loop" through the thread list we will not actually read from the target process and instead use the cached value the dac already read...which preserves the loop in in the thread list.  I have seen cases where the dac will loop infinitely trying to walk a linked list, and since this is all native code you have no chance to abort it.

~~~

Also there may be other problems.  They _tend_ to be rare to see, but I've definitely seen them happen (for example #303).  In ClrMD 1.1 I put a mild disclaimer that "hey if you do this it's not supported" on the scenario, but after years of seeing weird behavior my thinking now is: Please use `CreateSnapshotAndAttach` and if that is too big of a perf hit then you should consider something other than ClrMD.

**Comment by loop-evgeny** [comment]
Thank you, that's very helpful!

Yes, I know that `CreateSnapshotAndAttach` is the supported way, but it suspends the process for a while, which is often unacceptable. In our case, we'd rather take a tiny chance of something going wrong. I have not yet observed the target process crashing nor any obviously incorrect stack traces. Also, `CreateSnapshotAndAttach` only works on .NET Core 3.0 or later and, in case of Windows, on Windows 8.1/2012 or later - it might be nice to document that.

I have seen the process using ClrMd use a lot of CPU for a long time - I don't know if it was an infinite loop, as such - so to get around that we now run it using the `timeout` command on Linux whenever it's run automatically.

> if that is too big of a perf hit then you should consider something other than ClrMD

Do you know of anything other than ClrMD that can get stack traces of a .NET Core process on Linux without suspending the process? It seems like if the problem is in the DAC then any other tools would run into the same issues.

**Comment by leculver** [comment]
> Do you know of anything other than ClrMD that can get stack traces of a .NET Core process on Linux without suspending the process?

For Windows I'd suggest ETW events.  On Linux we have `lttng` support for collecting perf traces with stacks...or at least we did a while back.  There's also the new EventPipes feature from the CLR diagnostic team which is essentially ETW events without ETW.  However, I'm not sure if EventPipes can give you arbitrary stack traces (like ETW/lttng CPU stacks do).

In either case I would reach out to the CLR diagnostics team who might be able to answer your question.  Alternatively, I think both `lttng` and `EventPipe` is used by PerfView, you could always go pull up its source to see what options are available there.
