### ISSUE TITLE
Adding support for SOS SaveModule.

### ISSUE THREAD

**Issue by OmerRaviv** [Microsoft/clrmd#95]
I am trying to create an open-source ClrMD extension which is the equivalent to the SOS !SaveModule command. I'd be happy to contribute the result either to this repo if there's interest, or publish it as a separate ClrMD Extensions project.

The problem is, while I've been able to write my own code that partially works (it gets this right for some DLLs, but fails on others), there are a lot of unknowns in terms of how !SaveModule works internally. Unfortunately, after looking through https://github.com/dotnet/coreclr/tree/master/src/ToolBox/SOS/Strike it appears the code for !SaveModule is not publicly available as per https://github.com/dotnet/coreclr/issues/8363 . 

Is there any way to get access to the source code of !SaveModule, or a resource that explains how it works?

**Comment by discostu105** [comment]
Cool. I'd be very interested in that feature. Would make a perfect addition to https://github.com/Dynatrace/superdump.

**Comment by lasherer** [comment]
Hi Omer,

!savemodule has nothing to do with .NET, it is related to debug api.
I implemented it here:
https://github.com/rodneyviana/netext/blob/master/ClrMemDiagExt/Module.cs

Search for:

public bool SaveToStream(Stream ModuleStream)

Thanks,

Rodney


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dudikeleti** [comment]
Hi @lasherer,

Did you test your code with ngend modules?

I ask because I also wrote code that do the same but it not completely work for ngend modules (mscorlib.ni.dll for example). My exported assembly looks similar but not same as the required.

**Comment by lasherer** [comment]
It copies and rebases PE directories. It is equivalent to sos/psscorX !savemodule.

It is easy for you to test, download the extension and use:
!wmodule /name mscorlib* /saveto c:\modules\
And compare to sos output.



Sent from my mobile phone

On Mar 1, 2018, at 11:57 AM, Dudi Keleti <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @lasherer<https://github.com/lasherer>,

Did you test your code with ngend modules?

I ask because I also wrote code that do the same but it not completely work for ngend modules (mscorlib.ni.dll for example). My exported assembly looks similar but not same as the required.

**Comment by dudikeleti** [comment]
I'll try it after weekend and I'll update you. Thanks.

**Comment by lasherer** [comment]
I fixed a bug in save module to adjust the RVAs for memory stream only images (like generated serialization assemblies) not mapped to disk. Also adjusted issues with CLR headers

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
