### ISSUE TITLE
Support NativeAOT for writing WinDbg extensions

### ISSUE THREAD

**Issue by kevingosse** [microsoft/clrmd#962]
[NativeAOT](https://github.com/dotnet/runtimelab/tree/8e81d3a5bfd7639a197b51a1f65fcbba129d3b5f/samples/NativeLibrary) is slowly becoming mature, and is planned to be released with .NET 7. I believe this is a really convenient way to write WinDbg extensions, as it supports native exports without having to use ildasm-based hacks such as [UnmanagedExports](https://www.nuget.org/packages/UnmanagedExports).

I tried writing a proof of concept, and it works pretty well with a few changes to ClrMD: https://github.com/kevingosse/clrmd/tree/nativeaot

Mainly, adding `UnmanagedFunctionPointerAttribute` to some delegates, and exposing types that are useful to interact with WinDbg (for instance `DebugControl` to use `ControlledOutput`).

Is there any plan to actively support NativeAOT? If so, I'd be happy to contribute.

**Comment by leculver** [comment]
This is something that in general I would like to move to and support as well as possible.  I think my north star here is: "Building WinDbg (or lldb, or other debugger) extensions with ClrMD should be very easy and well supported."

I struggle a bit with how much of this to put directly into ClrMD and how much to write as a public domain sample.  I've specifically been trying to slim ClrMD down into just the managed debugging parts and not be an "Everything, all in one" library with things like Elf file reading, PEImage reading, PDB reading, etc.  It's just me that maintains this library and I have a lot of other responsibilities at microsoft too...so I haven't scaled well to keep all of these side pieces up to date.

So, it makes me nervous adding direct DbgEng hooks back into the library, marked public that I personally don't regularly use...I've found it's a quick way to get code rot.

With that said, if this approach leads to very easy to build DbgEng plugins that may be worth the cost of maintenance.

I'll take a close look at nativeaot windbg plugins in the next few weeks (including your linked tree, thanks for that!).  If it makes sense to add to the library I will, and if it doesn't I think at minimum it's reasonable for me to provide a public domain sample of template code that gets someone directly up and running with a dbgeng plugin using nativeaot instead of ildasm based things.

Thanks!

**Comment by kevingosse** [comment]
I have a working prototype of an LLDB extension written with ClrMD/NativeAOT, and I doubt it's possible to provide all the required components directly into ClrMD (if only because interacting with LLDB requires to call C++ methods that are not virtual, and for that I had to write an additional C++ library that does the translation). With that in mind, I think it makes sense to keep the ClrMD core as small as possible, and provide the WinDbg/LLDB interop bits as additional nuget packages.

**Comment by leculver** [comment]
I believe @mikem8361 has also been working on a SOS extensibility point which (when finished) will let folks write ClrMD based code that can be loaded anywhere SOS can.  That includes LLDB, dbgeng, and VS.  I don't think it's ready for consumption yet (but he can chime in), so that may also be an option for some folks.

> I doubt it's possible to provide all the required components directly into ClrMD (if only because interacting with LLDB requires to call C++ methods that are not virtual, and for that I had to write an additional C++ library that does the translation)

Yeah, agreed...my main goal with ClrMD is to build into the library the infrastructure which makes sense to be in ClrMD.  Other things would need to be in another library or sample code.  I mostly want to make sure ClrMD isn't getting in the way of those projects rather than building direct lldb support itself.  (Though Mike has been heading in that direction, so I would definitely check that out when that project is ready.)

**Comment by mikem8361** [comment]
The SOS extensibility (SOS doesn't just mean the old C++ sos.dll anymore) does allow the same CLRMD based commands to currently run under windbg, lldb and dotnet-dump and under Visual Studio real soon now.  Currently the public interfaces (Microsoft.Diagnostics.DebugServices assembly) are still not finished and official but there are many commands written like [DumpAsync](https://github.com/dotnet/diagnostics/blob/1e8e658f1bae02a0b5cb98336c09c7a18089bfa7/src/Microsoft.Diagnostics.ExtensionCommands/DumpAsyncCommand.cs#L16) and many others that are part of the standard command set across all the debuggers. In the fairly near future, it will be possible to write these commands in your own assembly and have the it loaded by SOS (currently only dotnet-dump analyze supports this via the DOTNET_DIAGNOSTIC_EXTENSIONS env var). When this is done it will enable all kinds of domain specific commands to help diagnose and solve issues across debuggers, platforms and OS's.

**Comment by leculver** [comment]
I'm working on this now: https://github.com/microsoft/clrmd/pull/1051

**Comment by leculver** [comment]
I have completed and checked in the basic support for NativeAOT.  I version bumped ClrMD to 2.3 for this change and some other reasons.  I'll also be shipping a Microsoft.Diagnostics.Runtime.Utilities NuGet package with the DbgEng helpers that I plan to keep up to date.

I'm resolving this generic issue now since ClrMD is now compatible with NativeAOT, but I don't expect the work is actually _done_ here.  I'm expecting a lot of work and iterations on the Utilities library, for example.  Please feel free to open new (more specific) issues if you run into trouble here.

I will have a NuGet package up by Jan 10th at the latest, probably pre-release versions before then.

**Comment by leculver** [comment]
FYI, I'm working to ship an updated ClrMD, and a new [Utilities](https://www.nuget.org/packages/Microsoft.Diagnostics.Runtime.Utilities) package with all of the IDebug* NativeAOT wrappings.  I ran into a snag getting NuGet packages built and had to wait until today when most folks are back from vacation.  I hope to have the issue resolved and new packages shipped soon.

**Comment by leculver** [comment]
(Final update).  Shipped as ClrMD/Utilities 2.3.
