### ISSUE TITLE
Unable to create DACLibrary for minidump from self contained app

### ISSUE THREAD

**Issue by pavel-faltynek** [microsoft/clrmd#988]
When trying to create runtime from self contained app minidump, like:

```
            const string Dump = @"dump.13600.dmp";
            using var target = DataTarget.LoadDump(Dump);
            var runtime = target.ClrVersions.First().CreateRuntime();
```

Getting an error:
`Microsoft.Diagnostics.Runtime.ClrDiagnosticsException: 'Failure loading DAC: CreateDacInstance failed 0x80131c4f'`
The DAC dll is located, `CLRDataCreateInstance` called for IXCLRDataProcess interface and then failing.

- This applies for windows app built as `<SelfContained>` with given `<RuntimeIdentifier>` (so the DAC dll is part of the published stuff).
- This applies for mini dumps created by (the latest) `createdump.exe` (with no other than process id parameters), e.g.: the one located in `c:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.3` for 32 bits.
- This does not apply for full dump (e.g. created via `taskmgr.exe` - either bitness).

The problematic dump can be loaded in WinDbg with no issues, `!sosstatus` reports expected DAC.
We would like to use also clrmd for such dump analysis.

**Comment by leculver** [comment]
Hello!  I have taken a look at this and found that there is a problem with dac requests in single file mode, but the underlying issue you reported is actually a bug in dotnet-dump.  This tool does not put the enough information into the dump file for any tool to correctly determine that we are looking at a .Net process.  Since I've fixed what I can out of ClrMD and reported a bug to the diagnostics team, I'm closing this issue.

For further updates, please check this bug:  https://github.com/dotnet/diagnostics/issues/3065

Thanks!
